### ISSUE TITLE
Problem with Uploading file to solid POD

### ISSUE THREAD

**Issue by Leoudayan** [jeff-zucker/solid-file-client#100] opened 2019-12-09 19:39 UTC
Hi, 
I am trying the following code to upload a file from my local server to the solid pod. But its giving me error. 

```
async function fileCheck() {
  try{
  let url = "https://manotest2.solid.open.ac.uk/public/fitness/";
  let localfile = "/data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/temp/check.txt"; 

  await fileClient.uploadFile(localfile,url).then(success => {
    console.log(`Uploaded ${localfolder} to ${url}.`);
  }, err => console.log(err) );

} catch(err) {
  console.log('FileCheck Error: ', err);
}
} 
```

Error:

> (node:2162) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substr' of null
>     at solid.auth.fetch.then.res (/data/web/block/node/solidblcn/solidbcn/node_modules/solid-file-client/dist/console/index.js:160:27)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:2162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:2162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bourgeoa** [comment] 2019-12-09 20:26
Your `url` is a folder and not a file.
As a detail `localfolder` is a misleading name.

**Comment by Leoudayan** [comment] 2019-12-09 21:17
> Your `url` is a folder and not a file.
> As a detail `localfolder` is a misleading name.

Thanks for your reply. My goal is to upload a file from the local server to the POD. Should i specify the name of the file in the url as well?

**Comment by Otto-AA** [comment] 2019-12-09 21:31
> let localfile = "/.../temp/check.txt"; 

I'm not really familiar with the old solid-file-client, but have you tried `let localfile = "./../temp/check.txt` (or `let localfile = "../temp/check.txt"`)? The triple ... seems weird to me.

**Comment by Leoudayan** [comment] 2019-12-09 21:49
> > let localfile = "/.../temp/check.txt";
> 
> I'm not really familiar with the old solid-file-client, but have you tried `let localfile = "./../temp/check.txt` (or `let localfile = "../temp/check.txt"`)? The triple ... seems weird to me.

Hi sorry its not the actual URl, i just dont wanted to include the entire path. It seems that it is confusing. I have updated it now. Please check it. @Otto-AA

**Comment by Otto-AA** [comment] 2019-12-09 22:13
The problem seems to be, that solid-file-client expects a location header on the response, but the response hasn't got one. I guess that the reason for it is, that the fetch method of the solid-auth-cli version used didn't support it. But I haven't verified that, and I also didn't check if the newer solid-auth-cli would provide it.

I don't know if someone will fix it, as we are close to the v1.0.0 release. I don't know if/how you could catch the error because this version of solid-file-client doesn't seem to properly reject the promise. Nonetheless, the file should be uploaded even if this error is thrown.

Here's the code which causes the error:
https://github.com/jeff-zucker/solid-file-client/blob/503c6057904e0c8307e808e9542ef12454f2dea5/src/index.js#L158-L161

**Comment by bourgeoa** [comment] 2019-12-09 22:50
Documentation explains that `uploadFile` only works in console mode.

```
Should i specify the name of the file in the url as well?
```
Yes

**Comment by jeff-zucker** [comment] 2019-12-09 23:46
You have not specified the local URL properly. All files addressed on the local filesystem *must* start with file:// followed by the absolute location of the file including the initial slash, so something like:
```
  file:///data/web/blockchain20.kmi.open.ac.uk/node/...temp/check.tx
```
Note the three slashes - two for the file protocol and one as the root folder of your local file system.

**Comment by jeff-zucker** [comment] 2019-12-09 23:50
@Otto-AA wrote
> The problem seems to be, that solid-file-client expects a location header on the response, but the response hasn't got one. I guess that the reason for it is, that the fetch method of the solid-auth-cli version used didn't support it. 

No, you've misunderstood what is going on.  He is uploading a file from the local file system to the Solid server.  The location header is part of what the Solid server sends back, it has nothing to do with fetching the local file.

**Comment by Otto-AA** [comment] 2019-12-10 09:06
> You have not specified the local URL properly. All files addressed on the local filesystem must start with file:// followed by the absolute location of the file including the initial slash, so something like:

Are you sure about that? To me it seems exactly the other way around:
```javascript
> fs.readFileSync('/home/a_a/test/test1.txt', 'utf-8')
'xyz\n'
> fs.readFileSync('file:///home/a_a/test/test1.txt', 'utf-8')
Thrown:
Error: ENOENT: no such file or directory, open 'file:///home/a_a/test/test1.txt'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'file:///home/a_a/test/test1.txt'
}
```

> The location header is part of what the Solid server sends back, it has nothing to do with fetching the local file.

The error was thrown in line 160: https://github.com/jeff-zucker/solid-file-client/blob/503c6057904e0c8307e808e9542ef12454f2dea5/src/index.js#L159-L160

It says that it "Cannot read property 'substr' of null" which means that `location` is null which means that the response didn't have a `location` header. But you are right that the cause of this could be somewhere else, and is not necessarily in solid-auth-cli. Maybe the server doesn't return a location header if it was an invalid request. So changing the url to include the file name may work

**Comment by Leoudayan** [comment] 2019-12-10 12:20
@jeff-zucker I am getting the same error @Otto-AA got when i specified file:///

```
{ Error: ENOENT: no such file or directory, open 'file:///data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/models/check.txt'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Promise (/data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/node_modules/solid-file-client/dist/console/index.js:272:22)
    at new Promise (<anonymous>)
    at Object.uploadFile (/data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/node_modules/solid-file-client/dist/console/index.js:271:12)
    at fileCheck (/data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/models/exp1.js:106:20)
    at fileClient.login.then.sessionSolid (/data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/models/exp1.js:76:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'file:///data/web/blockchain20.kmi.open.ac.uk/node/solidblcn/solidbcn/models/check.txt' }
```
Is there any solution for this?

**Comment by jeff-zucker** [comment] 2019-12-10 15:00
I'm sorry Leoudayan - we are working on the new version and I have lost
touch with how the old version works.  At this point, I'm afraid you might
need to wait until we finish the new version.  Some other things you can
try - use readFile() to read the local file and then createFile() to create
the remote file with the content from the readFile().  You may also be able
to use solid-shell which has other methods to transfer files from local to
remote.

**Comment by Leoudayan** [comment] 2019-12-10 16:03
Thank you for the reply Jeff. Will be looking forward for the new version.

**Comment by jeff-zucker** [comment] 2020-01-02 19:56
Version 1.0.0 is now available.  This issue should be fixed, but please re-submit if it is not.

**Closed by jeff-zucker** 2020-01-02 19:56 UTC
